### ISSUE TITLE
Question: In Lockdown Mode Xcode and Go Compiler Output Runs are Blocked

### ISSUE THREAD

**Issue by eopeter** [google/santa#1048]
In LockDown mode, when I build a project in Xcode or Go; it builds fine. When I attempt to Launch the project from Xcode or do a `go run .` on main.go for example, it gets blocked.

I know I need to add Compiler rules for `ld` or `code sign` and `go`; What is the best way to get around this?

Is there any docs on compiler allow listing?

**Comment by pmarkowsky** [comment]
Admittedly the docs aren't great here. But  assuming you have `EnableTransitiveRules` set to `<true/>` in your MDM config or your sync server has sent `"enable_transitive_rules": true`   in the preflight response you should just need to add a compiler rule. 

If you're managing the rules locally then you can just add a transitive allow rule with `santactl`. 

e.g. `santactl rule --allow --compiler --identifier <sha256 of your compiler / tool that generates binaries>`

Otherwise you need to specify the rule so your sync service can send it to your Santa instances.

**Comment by eopeter** [comment]
Thank you!!
