### ISSUE TITLE
UI configuration options

### ISSUE THREAD

**Issue by j-steig** [google/santa#1111]
We would like to add some configuration options to adjust the UI.

Ideally, these would be config flags that allow:

1. Point to a file location for the Santa Icon
2. Change the Title text at the top of the user screen. Currently this is `Santa`.
3. Hide publisher field.
4. Hide Identifier field.
5. Hide user field.

Alternatives:
It would be great to include a UI file that is an entirely custom file that is displayed. A configuration to use a custom UI HTML or Swift file would be ideal.

**Comment by pmarkowsky** [comment]
You can kinda do this now. In #870 we added the ability to get distributed notifications that allows you to trigger post-exec tool, enhance or replace the UI with your own. 

We have some users who've  used these notifications and silent mode to make their own app that displays what they want instead.

**Comment by russellhancox** [comment]
(I wrote this long comment yesterday but it failed to post properly)

At some point several years ago we tried to make a customizable UI by re-implementing the existing dialogs in HTML/JS/CSS and embedding this within the .app, while providing a config option to point at your own HTML file elsewhere on disk. The intention was that you'd copy the default file, customize it as you see fit and then point to your custom version. Unfortunately, we never shipped this feature because the resulting UI was a mess - accessibility features didn't work, copy/paste didn't work properly, tabbing through UI elements didn't work, etc. It was _very_ obvious that this wasn't a "normal" Cocoa dialog.

Swift is not an option; because it's compiled we'd be loading in compiled code as a plugin and this is _very_ tricky to do safely.

For the specific flag proposals:

> 1. Point to a file location for the Santa Icon

This isn't possible. Apple does provide a way to have an app change its icon but you have to register the possible set of icons in the app's Info.plist, which can't be modified after signing.

> 2. Change the Title text at the top of the user screen. Currently this is Santa.

I'm conflicted about this. Santa is installed on user's systems, its name will appear in various places in a way that cannot be changed (the app name in /Applications, all the component process names, etc.) and so having the UI present a different name could be confusing. Indeed, the tab switcher will show Santa while a dialog is open, so it's not still exposed to users.

> 3. Hide publisher field.
> 4. Hide Identifier field.
> 5. Hide user field.

These are very reasonable, though for ease I'd put them under a single key and allow _any_ of the fields to be hidden. Something like this:

```xml
<key>HideUIFields</key>
<array>
  <string>publisher</string>
  <string>identifier</string>
  <string>user</string>
  <string>parent</string>
</array>
```

**Comment by j-steig** [comment]
This is really good information. We are doing a bit of investigation to see if we could just spin up our own app for the UI. We can likely close this for now and if we go with suppressing the fields as part of the configuration I can open up a new Issue.

Thanks!
