### ISSUE TITLE
Allow events not being sent to sync server in Lockdown mode

### ISSUE THREAD

**Issue by p-harrison** [google/santa#1137]
There is another issue #1136 open about event uploads, but I suspect the cause of this one might be different so logging it separately.

We have most of our machines configured in Monitor mode with EnableAllEventUpload enabled and this works well excepting the issue mentioned above.  On our Lockdown machines we had EnableAllEventUpload disabled initially.  However to assist troubleshooting #1136 we enabled EnableAllEventUpload for our Lockdown machines as well by making a change to the configuration pushed from our MDM.  I can see the managed preference has pushed down to this test machine and it has been rebooted a number of times since, however the only events that are being uploaded from it are Blocks, no Allow Certificate/Binary/TeamID etc.

Confirmation that the managed preference change has been deployed to the device -
```
plutil -p "/Library/Managed Preferences/com.google.santa.plist"
{
  "ClientAuthCertificateCN" => "*************"
  "ClientMode" => 2
  "EnableAllEventUpload" => 1
  "FailClosed" => 1
  "MachineOwner" => "****************"
  "SyncBaseURL" => "https://******************"
  "SyncEnableCleanSyncEventUpload" => 1
}
```

Santa status output -
```
santactl status
>>> Daemon Info
  Mode                      | Lockdown
  Log Type                  | file
  File Logging              | No
  USB Blocking              | No
  Watchdog CPU Events       | 0  (Peak: 12.44%)
  Watchdog RAM Events       | 0  (Peak: 28.77MB)
>>> Cache Info
  Root cache count          | 133
  Non-root cache count      | 4
>>> Database Info
  Binary Rules              | 0
  Certificate Rules         | 6
  TeamID Rules              | 9
  SigningID Rules           | 6
  Compiler Rules            | 0
  Transitive Rules          | 0
  Events Pending Upload     | 0
>>> Watch Items
  Enabled                   | No
>>> Sync Info
  Sync Server               | https://*********************
  Clean Sync Required       | No
  Last Successful Full Sync | 2023/08/01 09:47:12 +0100
  Last Successful Rule Sync | 2023/08/01 09:47:12 +0100
  Push Notifications        | Disconnected
  Bundle Scanning           | No
  Transitive Rules          | No
```

**Comment by mlw** [comment]
Have done some digging, and I believe that the root cause is due to `EnableAllEventUpload`. You show that it is set in the config, however, it looks like Santa will take the value out of preflight and use that as the state going forward: https://github.com/google/santa/blob/main/Source/santasyncservice/SNTSyncPreflight.m#L100

I think instead Santa should only update this value if the key was actually set in the preflight response. E.g. something like:
```
  NSNumber *enableAllEventUpload = resp[kEnableAllEventUpload];
  if (enableAllEventUpload) {
    [rop setEnableAllEventUpload:[enableAllEventUpload boolValue]
                          reply:^{
                          }];
  }
  ```

As a test - can you set the preflight key `enable_all_event_upload` to  true? If I prevent this key from being updated on my system I see `ALLOW_XYZ` events come thru.

**Comment by p-harrison** [comment]
Yes you're right @mlw, I added enable_all_event_upload:true to PreFlight and two syncs later I'm now seeing events coming in such as ALLOW_TEAMID, ALLOW_CERTIFICATE from my machine in Lockdown.

My day-to-day work is with MDM, so I reflexively moved as much of the over-the-air configuration to the managed preferences pushed from MDM and only provide the bare minimum response in my PreFlight.

I presume this behaviour is probably not limited to the enable_all_event_upload configuration key?  I noticed while trying to test for #1136 that pushing a change from MDM to the ClientMode key (from Lockdown to Monitor) seems to be ineffective.  '/Library/Managed Preferences/com.google.santa.plist' shows ClientMode=>1 but 'santactl status' still shows Mode|Lockdown.

**Comment by mlw** [comment]
> I presume this behaviour is probably not limited to the enable_all_event_upload configuration key?

That's correct, there are a few keys that have the same issue. We'll be updating this so that they're all treated consistently.

> I noticed while trying to test for https://github.com/google/santa/issues/1136 that pushing a change from MDM to the ClientMode key (from Lockdown to Monitor) seems to be ineffective. '/Library/Managed Preferences/com.google.santa.plist' shows ClientMode=>1 but 'santactl status' still shows Mode|Lockdown.

I believe what you're describing is intended behavior. The mode Santa operates in is dictated by what the sync server most recently set in the preflight response, and this mode overrides what is in the static configuration file.

**Comment by p-harrison** [comment]
Great thanks Matt, it's starting to make sense to me!

I wonder if I could clarify a few points and I'll take a crack at fleshing out some of the documentation around this?
1. Where does Santa actually store it's 'running' config?  So for example PreFlight tells a machine to be in Lockdown mode, that's going into the database rather than Managed Preferences?
2. At what point does Santa reload configuration from Managed Preferences?  I recently pushed the MachineOwner key (via MDM) to all machines, after a few days I started to see the primary_user value being populated with what I'd set, so I'm wondering if it's just when the Santa services start or if there's a regular check or listener for changes.
3. Does Santa consider changes to all keys in Managed Preferences or just some?  As I mention I was able to effect a change using MachineOwner, but changing ClientMode did not have the desired effect.

On the ClientMode query, I wonder if there's an argument for a change here to allow people control it on-the-fly via Managed Preferences if they want to?  If the client_mode key could be made optional in the PreFlight response then ensure Santa regularly refreshes from Managed Preferences that should do it, and I think would have no impact on existing deployments.  full_sync_interval probably doesn't need to be mandatory in the PreFlight response either, again in my case I'd hope to set that in Managed Preferences via MDM.

**Comment by russellhancox** [comment]
> Where does Santa actually store it's 'running' config? So for example PreFlight tells a machine to be in Lockdown mode, that's going into the database rather than Managed Preferences?

Rules and events go in databases, config received from a sync server goes in /var/db/santa/sync-state.plist, all other config comes from Managed Prefs.

> At what point does Santa reload configuration from Managed Preferences?

For keys that support being refreshed while Santa is running (which is most, but not all), the OS tells us when the keys change so it should be nearly immediately after the profile installs.

> Does Santa consider changes to all keys in Managed Preferences or just some

Most, but not all. Keys that can be [set by a sync server](https://santa.dev/deployment/configuration.html#sync-server-provided-configuration) will override those from a profile when they've been provided. For the rest, nearly all support live refresh but there are a couple that are too complex to apply without restarting the daemon.

> On the ClientMode query, I wonder if there's an argument for a change here to allow people control it on-the-fly via Managed Preferences if they want to? If the client_mode key could be made optional in the PreFlight response then ensure Santa regularly refreshes from Managed Preferences that should do it, and I think would have no impact on existing deployments.

The `client_mode` key in a preflight response _is_ optional. If it isn't set, the mode is not changed. However, if the sync server has _ever_ set the client mode, changing the profile will not have any effect.

> full_sync_interval probably doesn't need to be mandatory in the PreFlight response either, again in my case I'd hope to set that in Managed Preferences via MDM.

This is a required key because it's the expected method for a sync server to deal with overload - if the server is struggling to keep up with sync demands it can request that clients sync less frequently to help reduce the load. We could modify the behavior to match that of `client_mode` but it will behave the same way: once the sync server has taken control of that setting it will not revert back to the profile.
