### ISSUE TITLE
Feature Request: System Notifications in Monitor Mode

### ISSUE THREAD

**Issue by jamiestrachan-shopify** [google/santa#1190]
Hi there,
We are making use of the System Notification for application block events.  This works great in `lockdown` mode.
I was wondering if it might be possible to get these event notifications while in `monitor` mode as well.
This could be controlled with a configuration item, similar to the `DisableUnknownEventUpload` configuration item.

Or, maybe I've missed something and this might already be possible?
Would notifications be generated if `enableAllEventUpload` was set? (I don't really want to do that, tho)

Thanks!

**Comment by mlw** [comment]
Hello - I'd like to clarify a bit about the request.

I ran a quick test and I am receiving distributed notifications when execs are blocked in `monitor` mode. 

Are you seeing issues with messages being sent on blocked execs? Or are you maybe asking for notifications to be sent on all execs (either blocked or allowed)?

**Comment by jamiestrachan-shopify** [comment]
Hello!
We have our clients configured with `EnableSilentMode` set to true, and are subscribed to the `com.google.santa.notification.blockedeexecution` Distributed Notification channel.
When our program is in Lockdown mode, our subscription callback gets invoked as expected.
However, when in Monitor mode, our callback does not get invoked.

Looking into the `/var/db/santa/santa.log` file, I see that in this situation, the events are logged as `decision=ALLOW` and `reason=UNKNOWN`.

For example (heavily redacted):
```
[2023-09-25T19:39:45.839Z] I santad: action=EXEC|decision=ALLOW|reason=UNKNOWN|sha256=...|cert_sha256=...|cert_cn=Developer ID Application: ...|teamid=...|pid=...|pidversion=...|ppid=...|uid=...|user=...|gid=...|group=...|mode=M|path=/Applications/Geany.app/Contents/MacOS/geany|args=/Applications/Geany.app/Contents/MacOS/geany
```

Now, that being said, we do still get events like this uploaded to our server! It's just the Distributed Notification that seems to be missing.

In this case, the application `geany` is not allowed because it is not in any allow list. We are not specifically blocking it with a rule.

Thanks!

**Comment by mlw** [comment]
I think there might be some misunderstandings here.

> For example (heavily redacted):
`[2023-09-25T19:39:45.839Z] I santad: action=EXEC|decision=ALLOW|reason=UNKNOWN|...`

Notifications are only sent when an execution is blocked, so no notification would be posted here since `decision=ALLOW`.

> Now, that being said, we do still get events like this uploaded to our server! 

This would be expected (either via normal logs collection, or by using something like the `EnableAllEventUpload` to have the events sent during client sync `EventUpload` phase)

> In this case, the application `geany` is not allowed because it is not in any allow list. We are not specifically blocking it with a rule.

This statement seems to be the key misunderstanding. In `Lockdown` mode, applications are denied by default unless an explicit allow rule exists. So when mentioned in the previous comment that the notifications were received when the host was in `Lockdown`, this would be expected because the application is blocked.

However in `Monitor`, applications are _allowed_ by default, blocking requires a specific rule to be set.

Tangentially, some things to note:

1. `EnableSilentMode` should have no effect on distributed notifications are posted. This basically only controls whether or not the GUI is displayed.
2. If a rule has a policy of `SILENT_BLOCKLIST`, this is currently setup to disable both GUI _and_ distributed notifications.

**Comment by jamiestrachan-shopify** [comment]
Alright, thanks for the response!
I will close the issue.
