### ISSUE TITLE
Why is Clean Sync Required Always YES Even When Sync Server Sends NO

### ISSUE THREAD

**Issue by eopeter** [google/santa#1239]
Under what conditions does Clean Sync Required in Santa Status becomes "NO"?

```
>>> Daemon Info
  Mode                      | Monitor
  Log Type                  | file
  File Logging              | Yes
  USB Blocking              | No
  Watchdog CPU Events       | 5  (Peak: 39.36%)
  Watchdog RAM Events       | 0  (Peak: 68.63MB)
>>> Cache Info
  Root cache count          | 22
  Non-root cache count      | 1
>>> Database Info
  Binary Rules              | 1614
  Certificate Rules         | 17
  TeamID Rules              | 203
  SigningID Rules           | 0
  Compiler Rules            | 7
  Transitive Rules          | 8
  Events Pending Upload     | 0
>>> Watch Items
  Enabled                   | No
>>> Sync Info
  Sync Server               | http://localhost:84833/v1/santa/
  Clean Sync Required       | Yes
  Last Successful Full Sync | 2023/11/20 14:41:45 -0500
  Last Successful Rule Sync | 2023/11/20 14:41:45 -0500
  Push Notifications        | Disconnected
  Bundle Scanning           | Yes
  Transitive Rules          | Yes
>>> Metrics Info
  Metrics Server            | https://localhost:4984/metrics/santa
  Export Interval (seconds) | 30
```

**Comment by mlw** [comment]
This seems like the same underlying issue as #1217 

If you run `sudo santactl status`, do you get the expected output"?

**Comment by eopeter** [comment]
It's always YES even with `sudo santactl status`

**Comment by mlw** [comment]
Thank you - confirmed in code this is ___not___ the same issue as #1217 .

I dug into the code and what happens is that once a clean sync is requested, it will remain that way until a clean sync has completed. I confirmed with @russellhancox that this is intended behavior.

---

For reference - quick anlysis of the code flow:

In `SNTSyncPreflight.m`, we set `self.syncState.cleanSync = YES` only if the server set the value in the preflight response: https://github.com/google/santa/blob/main/Source/santasyncservice/SNTSyncPreflight.m#L140
```
  if ([EnsureType(resp[kCleanSync], [NSNumber class]) boolValue]) {
    SLOGD(@"Clean sync requested by server");
    self.syncState.cleanSync = YES;
  }
```

In `SNTSyncPostflight.m`, we only remove the clean sync flag if a clean sync was performed: https://github.com/google/santa/blob/main/Source/santasyncservice/SNTSyncPostflight.m#L46
```
  // Remove clean sync flag if we did a clean sync
  if (self.syncState.cleanSync) {
    [rop setSyncCleanRequired:NO
                        reply:^{
                        }];
  }
```

`SNTCommandStatus.m` gets this information via the daemon XPC: https://github.com/google/santa/blob/main/Source/santactl/Commands/SNTCommandStatus.m#L133
```
  __block BOOL syncCleanReqd = NO;
  [rop syncCleanRequired:^(BOOL clean) {
    syncCleanReqd = clean;
  }];
```

Which is just grabbing it from the sync state dictionary in the configurator:
```
- (BOOL)syncCleanRequired {
  return [self.syncState[kSyncCleanRequired] boolValue];
}

- (void)setSyncCleanRequired:(BOOL)syncCleanRequired {
  [self updateSyncStateForKey:kSyncCleanRequired value:@(syncCleanRequired)];
}
```

fwiw, this code has the same behavior looking back in time to 2022.8:
https://github.com/google/santa/blob/2022.8/Source/santasyncservice/SNTSyncPreflight.m#L169
https://github.com/google/santa/blob/2022.8/Source/santasyncservice/SNTSyncPostflight.m#L45

**Comment by eopeter** [comment]
What does it mean to do Clean Sync: `we only remove the clean sync flag if a clean sync was performed`? Does it mean: Download all rules and upload all events? That is happening in my case and expect the flag to be set to NO. Sync Server sends CleanSync: NO in preflight.

```
 // Remove clean sync flag if we did a clean sync
  if (self.syncState.cleanSync) {
    [rop setSyncCleanRequired:NO
                        reply:^{
                        }];
  }
````

**Comment by eopeter** [comment]
Also, my sync server "NEVER" sends CleanSync=YES; always NO. Maybe the default value is YES

**Comment by mlw** [comment]
> What does it mean to do Clean Sync
> Does it mean: Download all rules and upload all events?

Realistically, this is up to the sync server implementation. In `SNTSyncRuleDownload.m`, we send along the current state of `cleanSync`: https://github.com/google/santa/blob/f499654951b98a5cce94ce46e2927d12a6b39b72/Source/santasyncservice/SNTSyncRuleDownload.m#L44-L49

This eventually passes thru to `SNTRuleTable.m` and will cause all existing rules to be deleted: https://github.com/google/santa/blob/f499654951b98a5cce94ce46e2927d12a6b39b72/Source/santad/DataLayer/SNTRuleTable.m#L416-L418

Since rules are expected to be cleared out on the host, the server is responsible for sending whatever the current state for the host should be: https://santa.dev/development/sync-protocol.html#rule-download

```
If either the client or server requested a clean sync in the preflight stage, the client is expected
to purge its existing rules and download new rules from the sync server.
```

> Also, my sync server "NEVER" sends CleanSync=YES; always NO. Maybe the default value is YES

The default is NO, but a clean sync is automatically requested if, for example, the database needs to be rebuilt (such as the first time Santa starts up and no database previously exists):

https://github.com/google/santa/blob/f499654951b98a5cce94ce46e2927d12a6b39b72/Source/santad/DataLayer/SNTRuleTable.m#L197

This gets picked up in the preflight request here: https://github.com/google/santa/blob/f499654951b98a5cce94ce46e2927d12a6b39b72/Source/santasyncservice/SNTSyncPreflight.m#L78-L81

I would assume that you can confirm the host is requesting a clean sync from the sync server logs.

The final piece of code you pasted, from `SNTSyncPostFlight.m`: https://github.com/google/santa/blob/f499654951b98a5cce94ce46e2927d12a6b39b72/Source/santasyncservice/SNTSyncPostflight.m#L45-L50

Since it is expected the `self.syncState.cleanSync` property is being set in `SNTSyncPreflight.m`, I'd expect for the if check to pass and the code inside be executed, resetting the value.

Are you by chance hitting any errors during syncing that is aborting the sync prior to the postflight phase being able to complete successfully? (e.g., what is the output of `santactl sync`?)

Finally, it might be worth checking the `sync-state.plist` on the host for sanity:
```
sudo plutil -extract SyncCleanRequired raw /var/db/santa/sync-state.plist
```

**Comment by eopeter** [comment]
The output of `santactl sync`
```bash
sh-3.2# santactl sync
SyncBaseURL is not over HTTPS!
Preflight starting
Clean sync requested by user
Performing request, attempt 1
Preflight complete
Event upload starting
Event upload complete
Rule download starting
Performing request, attempt 1
Received 1829 rules
Processed 1829 rules
Rule download complete
Postflight starting
Performing request, attempt 1
Postflight complete
Sync completed successfully
```
Status remains `Clean Sync Required       | Yes` after that and the following

```bash
sh-3.2# sudo plutil -extract SyncCleanRequired raw /var/db/santa/sync-state.plist
true
```

**Comment by mlw** [comment]
Ah, I think I finally see what's happening. 

A clean sync is being requested in Preflight request dictionary (since we know the key is `true` because on your output above): https://github.com/google/santa/blob/f499654951b98a5cce94ce46e2927d12a6b39b72/Source/santasyncservice/SNTSyncPreflight.m#L78-L87

What I was misreading earlier - The `self.syncState.cleanSync` property is only set if the key was set in the Preflight response dictionary from the server. You mentioned that the server is always responding with NO.

This means that Santa never completes a clean sync and will continue to request it until that is satisfied.

To get this back to the state you want, the server has to perform the clean sync, which is indicated by setting the key to true in the response dictionary.

**Comment by eopeter** [comment]
Ahh! That did it. The sync server sent down a CleanSync=true and that changed the Clean Sync status to NO. Thank you!!
