### ISSUE TITLE
Compiler Rule: How to Check?

### ISSUE THREAD

**Issue by eopeter** [google/santa#1242]
I wrote a compiler rule with policy `ALLOWLIST_COMPILER` for `Java` binary which is the parent of a blocked process.  I found the path to the parent process (java binary) and added the compiler rule but the binary (different hash each time) is still getting blocked with the message as shown below. How do I check that the compiler rule is in effect and should be working?

```bash
Santa

This application has been blocked

Path:       /Users/nm/idea/my-codeql/db-snapshot/working/copy-root/000114A8/bin/bash
Identifier: 9277832897d596e52980b41bfbc94c5fe73b47437cb26abd1ed312e0505a14ba
Parent:     java (59249)

More info:
http://localhost:93543/v1/santa/blocked/9277832897d596e52980b41bfbc94c5fe73b47437cb26abd1ed312e0505a14ba
```

**Comment by pmarkowsky** [comment]
There's a few ways to check that the compiler rule is in effect. 

1. Use `santactl fileinfo` on the generated binary. You should see an `Allowed (transitive)` in your case `/Users/nm/idea/my-codeql/db-snapshot/working/copy-root/000114A8/bin/bash` 

Also worth checking to if Java's reporting in as a compiler which you can do by running `santactl fileinfo <path to java>`.

2. Enable debug logging by adding to your application config `<key>EnableDebugLogging</key><true/>` and then run `log stream --predicate 'sender=="com.google.santa.daemon"'` to see the logs. 

You should see messages for when Santa tries to make a rule.

Admittedly there needs to be better logging here. For example if we miss a rename because the file's moved we'll tell you there's an error but not that the the file was not found.

**Comment by pmarkowsky** [comment]
@eopeter #1248 improves the debug logging for the compiler rules. When Santa 2023.10 is released that should help after you've enabled debug logging.

**Comment by eopeter** [comment]
I updated Santa to version 2023.9 and now see this when I sync without sudo (this is awesome by the way). What is wrong with the rules shown in the error? What is the right way to write a compiler rule? I am thinking the rule_type should be `BINARY` instead of `COMPILER`

```
santactl sync
SyncBaseURL is not over HTTPS!
Preflight starting
Performing request, attempt 1 (of 5 maximum)...
Preflight complete
Event upload starting
Event upload complete
Rule download starting
Performing request, attempt 1 (of 5 maximum)...
Ignoring bad rule: {
    identifier = a5938d9e5e9f4bbf84bd330a4ddd152b14480acd7ab9d8ef5982e457b3efc640;
    policy = "ALLOWLIST_COMPILER";
    "rule_type" = COMPILER;
    "time_stamp" = 1700513552;
}
Ignoring bad rule: {
    identifier = c7fe54274e6bda205aa0eda81d12b11216a8c080e0103e76cdcab7fae8ea3585;
    policy = "ALLOWLIST_COMPILER";
    "rule_type" = COMPILER;
    "time_stamp" = 1701194364;
}
Received 1855 rules
.
.
.
```
