### ISSUE TITLE
`contactsd` seem to be able to bypass santa's silent block on macOS Sonoma 14.1.1

### ISSUE THREAD

**Issue by tddschn** [google/santa#1266]
```
OS: macOS Sonoma 14.1.1 (Intel)

santactl version
santad          | 2023.10 (build 586760272)
santactl        | 2023.10 (build 586760272)
SantaGUI        | 2023.10 (build 586760272)
```

The binary I noticed to bypass silent block is `contactsd` (`/System/Library/Frameworks/Contacts.framework/Support/contactsd`)

```
sudo santactl rule --silent-block --path /System/Library/Frameworks/Contacts.framework/Support/contactsd
sudo santactl rule --check --path /System/Library/Frameworks/Contacts.framework/Support/contactsd
Blocked (Binary)

sudo killall contactsd # killed successfully, `ps auxww | command grep contactsd` confirms this
# but after a while (minutes, or days), contactsd was found to be running. 
```
I've used santa to block `contactsd` for months now, and it has been working as expected (no contactsd running after blocked and killed), and only recently I found contactsd running after blocked and killed.

I don't know if it also happens to other Apple binaries, but I think it's because `contactsd` has some kind of priviledge to run even when blocked?

**Comment by mlw** [comment]
Could you also please run:
```
santactl fileinfo /System/Library/Frameworks/Contacts.framework/Support/contactsd
```

**Comment by tddschn** [comment]
<details>
  <summary>fileinfo</summary>
  
santactl fileinfo /System/Library/Frameworks/Contacts.framework/Support/contactsd
Path                   : /System/Library/Frameworks/Contacts.framework/Support/contactsd
SHA-256                : 45dca31f73ba30800b2dc2028ac54f5320d4a233ce38da74c7630da42fae3038
SHA-1                  : dbe00c92326de2d80c47de51ab056bd3e8746abe
Bundle Name            : Contacts
Bundle Version         : 3631
Bundle Version Str     : 1.0
Signing ID             : com.apple.contactsd
Type                   : Executable (x86_64, arm64e)
Code-signed            : Yes
Rule                   : Blocked (Binary)
Signing Chain:
    1. SHA-256             : d84db96af8c2e60ac4c851a21ec460f6f84e0235beb17d24a78712b9b021ed57
       SHA-1               : efdbc9139dd98dbae5a9c7165a096511b15eaef9
       Common Name         : Software Signing
       Organization        : Apple Inc.
       Organizational Unit : Apple Software
       Valid From          : 2020/10/29 14:32:38 -0400
       Valid Until         : 2026/10/24 13:39:41 -0400

    2. SHA-256             : 5bdab1288fc16892fef50c658db54f1e2e19cf8f71cc55f77de2b95e051e2562
       SHA-1               : 1d010078a61f4fa4694aff4db1ac266ce1b45946
       Common Name         : Apple Code Signing Certification Authority
       Organization        : Apple Inc.
       Organizational Unit : Apple Certification Authority
       Valid From          : 2011/10/24 13:39:41 -0400
       Valid Until         : 2026/10/24 13:39:41 -0400

    3. SHA-256             : b0b1730ecbc7ff4505142c49f1295e6eda6bcaed7e2c68c5be91b5a11001f024
       SHA-1               : 611e5b662c593a08ff58d14ae22452d198df6c60
       Common Name         : Apple Root CA
       Organization        : Apple Inc.
       Organizational Unit : Apple Certification Authority
       Valid From          : 2006/04/25 17:40:36 -0400
       Valid Until         : 2035/02/09 16:40:36 -0500

</details>

---

I noticed that `contactsd` may run after macOS updates, and haven't noticed it running in other circumstances.

**Comment by mlw** [comment]
I need to clarify something. In the original post, you report:
```
I've used santa to block contactsd for months now, and it has been working as expected (no contactsd running after blocked and killed), and only recently I found contactsd running after blocked and killed.
```

But in the last comment you reported:
```
I noticed that contactsd may run after macOS updates, and haven't noticed it running in other circumstances.
```

Can you confirm if this is only happening after OS upgrade and/or reboot? Or is it happening even while the system has been up for some time?

**Comment by tddschn** [comment]
I think it only happened after reboot.

**Comment by mlw** [comment]
Thank you for clarifying. If you're only seeing this binary launch after reboots, the short answer here is that this is a limitation of the macOS API.

During what the `EndpointSecurity(7)` framework terms as "early boot" - that is, the period of time during which `launchd(8)` is bringing up user space and speculatively launching registered daemons - only 3rd party executions are held up until ES system extensions (such as Santa) are finished "registering". Because `contactsd(8)` is a platform binary, it is not held up during this "early boot" period and is allowed to freely execute without intervention from ES system extensions. This essentially means there is a race between products like Santa being started and the ability to block platform binaries like `contactsd(8)`.

Internally, we've chatted about an option to be able to reevaluate and kill live processes that started before Santa launched or were previously allowed but due to new rule sets should be blocked. Something like this - being able to kill platform binaries that launched during "early boot" - would be another argument in favor of such a feature. I'll get this issue filed publicly at least so the effort can be tracked.

Please feel free to reopen if you're seeing this seemingly bypass Santa rules after the system comes up.

**Comment by tddschn** [comment]
Thank you for writing the explanation! The current choice of not killing blocked binaries makes sense to me - I rarely reboot my Mac so killing them manually doesn't hurt. :)
