### ISSUE TITLE
Cannot see any log messages from asl logging framework.

### ISSUE THREAD

**Issue by iradization** [google/santa#184]
Hi, 
I've just deployed this project and played with it a little. However, I cannot see the file /var/log/santa.log and it seems like non of the log messages are forwarded to this file.. perhaps it's something to do with the fact that ASL is deprecated (my OS version is 10.12).

thanks

**Comment by arubdesu** [comment]
Hey there, as of [this release](https://github.com/google/santa/releases/tag/0.9.18) logs are in `/var/db/santa`.

**Comment by iradization** [comment]
Yes, I've noticed this point.. but still, couldn't find the log files even in `/var/db`.. it seems like apple stopped supporting asl. according to [this](https://forums.developer.apple.com/thread/68794) thread, the asl is deprecated and replaced by unified log, and I suppose that's why it doesn't work on 10.12... were you managed to see the log files yourself while running under macOS Sierra ?

**Comment by russellhancox** [comment]
ASL is technically deprecated but all the calls still work and depending on the SDK used to build may redirect ASL calls to ULS (unified logging system). We're still building with the 10.11 SDK so that the logs are still sent to syslogd and can be configured to redirect to a file.

If the logs are not appearing, check that `santad` is running, that the ASL config file exists at `/etc/asl/com.google.santa.asl.conf` and that the second line of that file contains 
`> /var/db/santa/santa.log`

**Comment by russellhancox** [comment]
Please re-open if this is still an issue.
