### ISSUE TITLE
Service dependency between santad and the driver module.

### ISSUE THREAD

**Issue by iradization** [google/santa#199]
Hi, 

Is it possible to avoid a scenario where the kernel module is being unloaded (using kextunload) while the santad is still up. 

In my opinion, when the root user wishes to unload the product, he may do so by telling launchctl to unload the service of santad, and this command will seep through all other components, and the driver among them.   

From apple documentation, I deduce that one KEXT can take reference on another KEXT when it uses symbols that reside on the other KEXT:

"Any KEXT can declare that it is dependent upon any other KEXT. The developer lists these dependencies in the OSBundleLibraries dictionary in the module’s property list file."

However, for this task we need to do the other way around, by marking refs from other entities to the driver, and those entities aren't necessarily other drivers (in our case, it's santad).

In windows it's doable since you may define all entities as services, and one can easy link between 2 such services disregarding if they're user-space processes or kernel modules.

is it possible in MacOS ?

**Comment by russellhancox** [comment]
> Is it possible to avoid a scenario where the kernel module is being unloaded (using kextunload) while the santad is still up.

We _could_ change santa-driver so that it refuses to unload while a process is still connected but instead of doing this santa-driver sends a message to santad telling it to shutdown, which will cause launchd to reload it and in turn the driver will be reloaded. This allows for graceful reloading.

> In my opinion, when the root user wishes to unload the product, he may do so by telling launchctl to unload the service of santad, and this command will seep through all other components, and the driver among them.

There is a reason to keep santa-driver loaded even when santad isn't running, namely that it will collect data about started processes so that when santad does load it can log out the data it has and use this for correlating future process starts.

> However, for this task we need to do the other way around, by marking refs from other entities to the driver, and those entities aren't necessarily other drivers (in our case, it's santad). .... Is is possible in MacOS ?

Not in the way you mention. We _could_ change the driver so that it would unload itself when santad goes away or adding hooks in santad so that it will unload the driver (assuming it is SIGTERM'd rather than SIGKILL'd) but for the reasons above that isn't desirable.
