### ISSUE TITLE
Long paths bypass Santa

### ISSUE THREAD

**Issue by codido** [google/santa#229]
vn_getpath() may return errors, for instance, if the path is longer than MAXPATHLEN (there may be other cases as well).
In such cases the executable will be allowed to execute. 

For example, the following execution of a new binary isn't blocked:
```
cd /tmp
for i in {1..4}; do mkdir `python -c "print 255 * 'x'"`; cd $_; done
echo "int main() { return 0; }" | gcc -x c -
./a.out
```

**Comment by russellhancox** [comment]
Thank you for the report and simple repro steps, we'll get a new release created ASAP.

**Comment by russellhancox** [comment]
This fix has been included in the v0.9.21 release. Thanks again!

**Comment by codido** [comment]
Thanks!

Just wondering - can't vn_getpath() fail for reasons other than the output length? For instance, if one of the parents happened to move?

**Comment by russellhancox** [comment]
It can yes but one of our design decisions is that bugs or failures shouldn't cause unexpected blocked executions. The "too long" case is OK to block because you can't run these things via Finder or absolute path anyway and it's very trivial to do.

For the time being we're being overly cautious in allowing things that are unexpected but I expect we'll tighten these up as we get closer to 1.0.
