### ISSUE TITLE
Can Google Santa deal with non-binary malware or is it out of the project's scope?

### ISSUE THREAD

**Issue by nsuchy** [google/santa#261]
I recently came across a keylogger (seems to be a proof of concept - https://github.com/NullArray/Keylogger/blob/master/logger.py) written in Python. This is particularly troublesome in the event that someone released a sorta useful python library and then hides the keylogger installation code inside which runs the first time you use the libary then covers itself up afterwards, which with some work by a threat actor, the malware could install itself persistently on your system and run as a silent Google or YOUR_COMPANY_NAME_HERE approved Python binary running the malicious python code. The same could happen with any other interpreted programming language. This seems to be a security nightmare in an environment where binary whitelisting is needed to protect data. Thoughts?

**Comment by tburgin** [comment]
That is a good question. The short answer is: No, it is out of scope.
The longer answer is: It depends how you are running the code. Let me explain.
Santa gets in the middle of all exec() calls. If the file on disk has its executable bit set, it can try and exec.

For example, I have a the following python script.
```sh
⇒  cat runme.py
#!/usr/bin/python

print "Yikes!"
```
I can set its permissions so that it can be executed.
```sh
⇒  chmod a+x runme.py
ls -la runme.py
-rwxr-xr-x  1 tom  admin  34 May 15 17:18 runme.py
```
Let's see what Santa thinks of it.
```sh
⇒  santactl fileinfo runme.py
Path                   : /Users/tom/Desktop/santa_scopes/runme.py
SHA-256                : 8bb4ce373f52a36d090158b5b037da5d9141450bd38ca737292eeb695ec6acf2
SHA-1                  : f58b22ca855bf5a74bf98293ebeff44ef079a11d
Type                   : Script
Code-signed            : No
Rule                   : Whitelisted (Scope)
```
If this file tries to execute Santa will allow it. Santa didn't find any [rules](https://github.com/google/santa/blob/master/Docs/details/rules.md) for the hash, and it is not code signed so no rules for the signing certificate (only Mach-O binaries can be code signed). Santa does however find a [scope](https://github.com/google/santa/blob/master/Docs/details/scopes.md) that the file falls into. The file is "Not a Mach-O", so Santa will allow it to execute.
```sh
⇒  ./runme.py
Yikes!
```
But, what if there was a rule added for the file? I went ahead and added a blacklist rule for the `SHA-256` of the file. Because Santa evaluates rules from the most specific to the least specific, it now will block the execution of the file.
```
⇒  santactl fileinfo runme.py
Path                   : /Users/tom/Desktop/santa_scopes/runme.py
SHA-256                : 8bb4ce373f52a36d090158b5b037da5d9141450bd38ca737292eeb695ec6acf2
SHA-1                  : f58b22ca855bf5a74bf98293ebeff44ef079a11d
Type                   : Script
Code-signed            : No
Rule                   : Blacklisted (Binary)
⇒  ./runme.py
zsh: operation not permitted: ./runme.py

Santa

This application has been blocked from executing
because it has been banned.

Path:       /Users/tom/Desktop/santa_scopes/runme.py
Identifier: 8bb4ce373f52a36d090158b5b037da5d9141450bd38ca737292eeb695ec6acf2
Parent:     zsh (90012)
```
AHAH! We have done it! We have blocked the file from running. Well not so fast...We have blocked just that file from being executed. Any python interpreter that is allowed to run can easily run this code.
```sh
  santactl fileinfo /usr/bin/python
Path                   : /usr/bin/python
SHA-256                : cfa814e36160e9a292e114e0d0e9efd9782ee596985be58dae0a41f0483bb8a8
SHA-1                  : 07565e53061f5a9588ab362dc987e5d56b8b8127
Type                   : Executable (x86_64, i386)
Code-signed            : Yes
Rule                   : Whitelisted (Certificate)
Signing Chain:
    1. SHA-256             : 2aa4b9973b7ba07add447ee4da8b5337c3ee2c3a991911e80e7282e8a751fc32
       SHA-1               : 013e2787748a74103d62d2cdbf77a1345517c482
       Common Name         : Software Signing
       Organization        : Apple Inc.
       Organizational Unit : Apple Software
       Valid From          : 2013/04/12 18:34:35 -0400
       Valid Until         : 2021/04/12 18:34:35 -0400

    2. SHA-256             : 5bdab1288fc16892fef50c658db54f1e2e19cf8f71cc55f77de2b95e051e2562
       SHA-1               : 1d010078a61f4fa4694aff4db1ac266ce1b45946
       Common Name         : Apple Code Signing Certification Authority
       Organization        : Apple Inc.
       Organizational Unit : Apple Certification Authority
       Valid From          : 2011/10/24 13:39:41 -0400
       Valid Until         : 2026/10/24 13:39:41 -0400

    3. SHA-256             : b0b1730ecbc7ff4505142c49f1295e6eda6bcaed7e2c68c5be91b5a11001f024
       SHA-1               : 611e5b662c593a08ff58d14ae22452d198df6c60
       Common Name         : Apple Root CA
       Organization        : Apple Inc.
       Organizational Unit : Apple Certification Authority
       Valid From          : 2006/04/25 17:40:36 -0400
       Valid Until         : 2035/02/09 16:40:36 -0500
```
```sh
⇒  python runme.py
Yikes!
```
This goes for all interpreted languages as well as shell scripts.

It comes down to: there is no scalable way to run in lockdown mode, blocking unknown interpreted scripts, while maintaining a whitelist of good scripts. Even if there was, we would then have to understand how each interpreter works internally and try and trap certain actions, like running code from an arbitrary file.

There are also some more subtle reasons why Santa does not consider scripts in scope, but the above explanation is the gist of it.
