### ISSUE TITLE
incomplete administrative events sync data sent in monitor mode

### ISSUE THREAD

**Issue by thehesiod** [google/santa#327]
We're using upvote to track all our users in monitor mode.  We will go to the admin events page, which we've enhanced, to track what the santa action performed was (ex: ALLOW_UNKNOWN), and what the current state of the ruleset is (ex: Certificate Globally Whitelisted).

The issue from what I gather, is that if you see a new binary that is signed, it will upload the event with the blockable id for the binary, as well as the certificate info.

The issue is that if you see a new blockable, signed with the same cert chain, the event sent to the upvote server does not have any of the certificate information.  This means we cannot tell if the blockable will be blocked, or whitelisted if we disable monitor mode for this event.

**Comment by russellhancox** [comment]
I'm not sure I follow.

Santa uploads events for all binaries that are blocked or unknown. The
events include a lot of data, including the full signing chain.

Upvote does a lot of deduplication, partially because we have a _very_
large fleet and didn't want to waste storage space. However, if the signing
chain has been uploaded once, future blockables signed with the same chain
will link to the existing entries for that chain, so you have all the data
still.

**Comment by russellhancox** [comment]
> From what I've seen using santactl sync locally in monitor mode, is that if the binary is trusted, events are not uploaded to upvote on a sync

This is correct, Santa doesn't send events to a sync server for binaries that are explicitly whitelisted (whether by certificate or binary), it only uploads events for executions that are denied or are allowed _because the machine is in monitor mode but would be blocked in lockdown_. We don't bother sending events for these things because for our purposes a sync server exists to allow us to whitelist things that would be blocked, we use the logs for tracking actual executions.

**Comment by thehesiod** [comment]
the issue in this case is that it seems santa did send the new binary event to upvote, but did _not_ send the **same** cert chain, so upvote has no idea that the new binary has the same cert chain.  I'll update this issue when I get some hard evidence.
