### ISSUE TITLE
Question about Transitive Whitelisting

### ISSUE THREAD

**Issue by ameyah** [google/santa#363]
Not really an issue, but seeking some answers:

What is transitive whitelisting?
From the way I understand it by going through the code and some common sense, if we whitelist Xcode for example, then all builds created by Xcode are whitelisted. Is this correct?

If yes,
1. Are the transitive whitelist rule time sensitive?
2. Are they erased on santad restart? Or after a sync / clean sync?
3. Does the same apply to package installers (thinking about Munki or even `/usr/sbin/installer`)?

Thank you!

**Comment by russellhancox** [comment]
> What is transitive whitelisting?

It was written to handle compilers and the like so developers can work in lockdown mode. It's lowering the security level but is good for cases where you'd otherwise put people on monitor mode.

> if we whitelist Xcode for example, then all builds created by Xcode are whitelisted. Is this correct?

Not quite: while we have some plumbing in place to make that work, currently it's disabled so the transitive mode only applies to the writing process. So you'd need to mark ld (or codesign) as a compiler as that's usually the final writing process in a compile. 

The reason for this is that to let you mark Xcode and have that apply, for every file write we'd have to scan up each parent in the process tree until we find one that's marked as a compiler or we find launchd (which we'd never let be marked as a compiler). That's likely to cause noticeable performance impact, so we've never enabled it. On top of that, marking Xcode as a compiler is risky as it's much easier to abuse than just marking the component pieces like ld.

> 1. Are the transitive whitelist rule time sensitive?

The rules will be deleted when they're more than 6 months old as long as there are 500000 such rules. This is just to keep the database from growing very large. We didn't see any reason to remove the rules otherwise, 

> 2. Are they erased on santad restart? Or after a sync / clean sync?

The process of checking for old rules happens whenever new rules are added.

> 3. Does the same apply to package installers (thinking about Munki or even /usr/sbin/installer)?

Transitive whitelisting only happens for binaries that you've added "COMPILER" rules for (which a sync server can do and so can the santactl/rule command). You could add such a rule for `installd` (which is what does the real work triggered by installer) if you wanted to, though I think that would be a bad idea.

**Comment by ameyah** [comment]
This is helpful. Thank you :)
