### ISSUE TITLE
More details on FCM setup

### ISSUE THREAD

**Issue by ameyah** [google/santa#365]
Hello,

I am exploring the FCM feature in Santa. I have a few questions:

1. As per Santa docs, the `fcm_token` should be pushed from the sync server. As per my understanding the way FCM works is: client generates the FCM token and sends it to the server which is then used by the server to send FCM messages. I don't have first-hand experience with FCM, so I might be incorrect.

2. If the `fcm_token` has to be generated from the server, can anyone point me to an API document for reference?

Thanks so much!

**Comment by russellhancox** [comment]
I need to look into this, I'll get back to you.

**Comment by ameyah** [comment]
Checking in if you got a chance to look @russellhancox ?

**Comment by russellhancox** [comment]
Sorry, I've been trying to find out how you can use this but don't have anything good to report yet. It seems that the particular FCM API we used when we implemented this is not publicly supported and switching to one of the other APIs is not a simple undertaking as they work quite differently. Hence Upvote was released with all of the FCM support removed.

It looks like the simplest option is to switch to using FCM's APNS API but that would mean having to re-sign all releases of Santa so that you'd be able to use your own APNS certificate, I think, so it's not an approach I'm particularly keen on. I'm investigating whether there's another FCM API we can switch to that wouldn't involve such re-engineering.

**Comment by ameyah** [comment]
Appreciate the update @russellhancox :)

**Comment by pmarkowsky** [comment]
Marking this as closed since it's almost 4 years old. Please feel free to reopen.
