### ISSUE TITLE
"Critical system binaries" approach is fundamentally flawed

### ISSUE THREAD

**Issue by mpsrig** [google/santa#377]
As far as I can tell, there's nothing preventing Apple from restructuring components of their OS and causing more issues like #375 and #295 without any warning.

Even without Apple doing anything, it seems possible or even likely that other such issues will be uncovered in the wild.

Is it possible to redesign the system to not need these manual entries and thereby systematically eliminate this class of bugs? 

(One naive approach I thought of would be having a mode where anything that is part of the OS is trusted by default)

**Comment by russellhancox** [comment]
> anything that is part of the OS is trusted by default

How do you do that, securely, without checking the code signature of the binary in question? We can't trust based on path, we can't scan every single binary to check if it's part of the system beforehand and we can't maintain lists of system binaries because that's more error-prone than what we have now.

The good news is that from macOS 10.15 onwards Santa will operate in a fundamentally different way that will remove this class of bug entirely.
