### ISSUE TITLE
clean sync required

### ISSUE THREAD

**Issue by weiminm** [google/santa#452]
Hi.

After install of santa and import of the example plist, the clean sync required seems to be default of yes. Based on the santa readme docs, this should be a No.
Also, setting the field clean_sync to true/false in moroz doesn't seem to cause this flag to change when a server sync is run. 

>>> Sync Info
  Sync Server               | https://santa:8080/v1/santa
  Clean Sync Required       | Yes
  Last Successful Full Sync | Never
  Last Successful Rule Sync | Never
  Push Notifications        | Disconnected
  Bundle Scanning           | No
  Transitive Whitelisting   | No

**Comment by russellhancox** [comment]
>  install of santa and import of the example plist, the clean sync required seems to be default of yes. Based on the santa readme docs, this should be a No.

This is caused by Santa's database initialization code - if the database doeesn't exist on startup it is created and the cleanSync flag is set to YES so that all of the sync code is aware that this is a first-time sync. Santa tells the server it would like a clean sync so that the server knows to _forget_ any sync cursor it might have. Once a successful sync has happened, the flag will be set to NO.

> Also, setting the field clean_sync to true/false in moroz doesn't seem to cause this flag to change when a server sync is run.

It appears moroz doesn't handle the clean sync flag at all, partially because it doesn't have per-machine state and will always send the full set of rules on every single run. However, as long as a sync is successful, the flag should be cleared. If you manually sync with `sudo santactl sync` does it return success or an error?

**Comment by weiminm** [comment]
Hi!

Thanks for replying so quickly. Here is my santactl sync, I don't see any errors, however the clean sync required flag doesn't change to false.

sudo santactl sync --debug
Missing Machine Owner.
Clean sync requested by user
Server Trust: /O=(null)/OU=(null)/CN=santa/SHA-1=
Preflight complete
Event upload complete
Added 4 rules
Rule download complete
Postflight complete
Sync completed successfully

**Comment by russellhancox** [comment]
> however the clean sync required flag doesn't change to false

How are you checking this?

**Comment by weiminm** [comment]
using the santactl status command.

**Comment by weiminm** [comment]
I updated some rules and did a sync but the old rules look like they didn't get removed from the endpoint. I understand you now.

**Comment by russellhancox** [comment]
> I updated some rules and did a sync but the old rules look like they didn't get removed from the endpoint. 

I don't believe Moroz handles rule deletion properly. Santa's syncing is designed so that the server is fully in control of the rules, updated rules will overwrite existing rules and rules can be deleted.

That `santactl status` is still showing a clean sync is required sounds like a possible bug but not one I'm able to reproduce.

**Comment by weiminm** [comment]
That's weird indeed, I am using the latest release of both santa and moroz.

**Comment by weiminm** [comment]
I created a machine specific .toml file and now I can see there is an extra line in the debug when I set the clean_sync = true in the machinename.toml file

sudo santactl sync --clean --debug
**Clean sync requested by user**
Server Trust: /O=(null)/OU=(null)/CN=santa/SHA-1=
Preflight complete
Uploaded 4 events
Event upload complete
Added 1 rules
Rule download complete
Postflight complete
Sync completed successfully
