### ISSUE TITLE
Monitor mode not uploading ALLOW_UNKNOWN events

### ISSUE THREAD

**Issue by j-steig** [google/santa#739]
It looks like ALLOW events might not be included in what is uploaded to a Sync Server.

Testing the software, I'm not seeing anything being uploaded in Monitor mode. Switching to Lockdown generates the events on a listening Sync Server.

Looking at the code, it looks like the actions are limited to ALLOW: https://github.com/google/santa/blob/main/Source/santad/SNTExecutionController.m#L168

And then it only uploads if the action is not ACTION_RESPOND_ALLOW or ACTION_RESPOND_ALLOW_COMPILER
https://github.com/google/santa/blob/main/Source/santad/SNTExecutionController.m#L241

Am I missing a setting to enable Monitor mode to upload events when they are Unknown? It looks like the documentation says it should be sending these up, and it looks like we had older versions that uploaded them so I'm wondering if there was a commit that prevented ALLOW_UNKNOWN from being bundled with the events to sync.

**Comment by tburgin** [comment]
The ALLOW_UNKNOWN events should be added to the events.db in Monitor mode as long as a sync server set. However, they will not be uploaded to the sync server immediately, only on the next sync. The DENY events are added to the  events.db and uploaded immediately so sync servers can handle the blocking event.

**Comment by russellhancox** [comment]
The first part you linked to on line 168 is for the response sent to ES, to allow or deny execution.

The second part, on line 241 handles logging denied executions, generating GUI notifications and out-of-band uploading pending events to the sync server. This last part is only done when execution is denied so that the server has the data before the user is presented the GUI notification so that if the notification links to a web page with details about the blocked binary it will have something to show. However, if this case is not hit, the event is still stored in the database as long as a sync server is configured, unless execution was _explicitly_ allowed (see lines 194-238) and these events should be uploaded whenever a full sync next occurs.

The only recent change we've made in this area is to not store events in the database if there is no sync server configured, to avoid filling up a database on disk with events that will never be uploaded. But if you have a sync server configured we should be generating events for both blocked executions and "would-be-blocked-in-lockdown" executions, so if that's not working there may be a bug.

**Comment by j-steig** [comment]
Is there a way of inspecting the events.db to see what should be in there? I'm running `sudo santactl sync` to force a sync and have seen no events uploaded and no log of an attempt.

**Comment by russellhancox** [comment]
`santactl status` has a field showing "Events Pending Upload". I'd also double check the log to make sure you're seeing executions with `action=EXEC|decision=ALLOW|reason=UNKNOWN`

**Comment by j-steig** [comment]
`[2022-03-02T19:03:22.575Z] I santad: action=EXEC|decision=ALLOW|reason=UNKNOWN|sha256=64bb9e77205588e7562410a9e8561627e3f6c271f14c612f8be8889497f5d661|cert_sha256=aaaa3958bfd19668fd819d8616f59445ff155b8317a2dcae8d38eccae4d047a4|cert_cn=Developer ID Application: Linebreak SL (DCMDDJEW9X)|pid=2561|pidversion=6088|ppid=1|uid=501|user=jesse|gid=20|group=staff|mode=M|path=/Applications/CloudApp.app/Contents/Resources/mac/CloudApp Helper.app/Contents/MacOS/CloudApp Helper|args=/Applications/CloudApp.app/Contents/Resources/mac/CloudApp Helper.app/Contents/MacOS/CloudApp Helper --list-permissions
jesse@Jesses-MBP santa % sudo santactl sync                                         
Password:
Missing Machine Owner.
Received 33 rules
Processed 33 rules
Sync completed successfully
jesse@Jesses-MBP santa % 
jesse@Jesses-MBP santa % 
jesse@Jesses-MBP santa % 
jesse@Jesses-MBP santa % sudo santactl status
>>> Daemon Info
  Driver Connected          | Yes
  Mode                      | Monitor
  File Logging              | Yes
  Watchdog CPU Events       | 0  (Peak: 3.97%)
  Watchdog RAM Events       | 0  (Peak: 63.08MB)
>>> Database Info
  Binary Rules              | 0
  Certificate Rules         | 33
  Compiler Rules            | 0
  Transitive Rules          | 0
  Events Pending Upload     | 0
>>> Sync Info
  Sync Server               | https://kepler.kepler-m1s7.jesse-steig.us.spin.dev/santa/
  Clean Sync Required       | No
  Last Successful Full Sync | 2022/03/02 12:38:12 -0700
  Last Successful Rule Sync | 2022/03/02 12:38:12 -0700
  Push Notifications        | Disconnected
  Bundle Scanning           | No
  Transitive Rules          | No`

**Comment by j-steig** [comment]
Removed the URL for the Sync Server, but I'm seeing other events hit that server.

**Comment by tburgin** [comment]
Can you run a few programs that result in `decision=ALLOW|reason=UNKNOWN` logs, then check `santactl status` for `Events Pending Upload`? Do this before syncing so we can see if the events are being stored.

**Comment by tburgin** [comment]
There is a cache that will remember ALLOWs for the lifetime of the `com.google.santa.daemon` process, or is the cache is purged which can happen due to a number of different triggers. Subsequent executions of the cached ALLOWed execution will not generate an event in the event.db (though it does still log).

You can kill Santa as a test to see if reseting the cache allows your `decision=ALLOW|reason=UNKNOWN` events to be stored.
```
sudo killall com.google.santa.daemon
```

**Comment by j-steig** [comment]
I killed the daemon and then run an app right after that that showed an `Event Pending Upload`.

After waiting for the sync timer, there was no call to `/eventupload/#{machine_id}`.

I did see calls to 'preflight', 'ruledownload' and 'postflight'. After seeing these calls, the `Events Pending Upload` dropped back down to 0.

Is there another way to force an event to upload?

**Comment by j-steig** [comment]
One thing to note is that I've factory reset my test device and then attempted to upload an event with no success in Monitor mode also.

**Comment by russellhancox** [comment]
Interesting - the fact that the events are being removed suggests that the event upload step _is_ being run as there are only 2 cases where events are removed:

1. The events are successfully uploaded
2. A clean sync is requested (either by the server or the client), in which case we skip the upload step but clear out the events that would have been uploaded.

Could you try the test again but this time once there is an event pending (as reported by `santactl status`), try running `sudo santactl sync --debug` so we can see if it starts the event upload step?

**Comment by j-steig** [comment]
`jesse@Jesses-MBP santa % sudo santactl sync --debug
Preflight starting
Missing Machine Owner.
Performing request, attempt 1
Server Trust: /O=(null)/OU=(null)/CN=real_cn_name_here/SHA-1=b8c46b92833fcfa2ecaef17bb1a232a063e23280
Clean sync requested by server
Preflight complete
Event upload starting
Event upload complete
Rule download starting
Performing request, attempt 1
Received 539 rules
Processed 539 rules
Rule download complete
Postflight starting
Performing request, attempt 1
Postflight complete
Sync completed successfully`

**Comment by russellhancox** [comment]
Aha:

`Clean sync requested by server`

Your server is requesting a clean sync, which is causing Santa to skip uploading events. Which server are you using, and can you stop it from doing that?

**Comment by j-steig** [comment]
I absolutely can stop it from doing that! Give me a minute to test.

**Comment by j-steig** [comment]
That did it! Thanks for helping me figure this one out!
