### ISSUE TITLE
PrinterProxy crashing on macOS Ventura

### ISSUE THREAD

**Issue by meta-github** [google/santa#880]
White testing beta releases of macOS Ventura, we have observed, that PrinterProxy did not start:

Exception Type:  EXC_CRASH (SIGKILL (Code Signature Invalid))

We have observed that PrinterProxy should have an ad-hoc signature, but somehow Santa replaces the binary and the resulting binary is unable to start on macOS Ventura.

Steps to reproduce on a system with macOS Ventura and Santa enabled:
- remove app for a printer in ~/Library/Printers
- start a print dialog using the same printer (app will be recreated)
- the app for your printer will not open and it will crash if you start it manually
- verify the code signature of the PrinterProxy: on macOS Ventura it should be adhoc signed, but it is not

The same works flawlessly and without a crash after Santa is disabled.

Santa version is 2022.7.

**Comment by np5** [comment]
This could be caused by the `EnableBadSignatureProtection` option in Santa. Could you run `santactl fileinfo` on the newly created app, and post the result here ?

**Comment by meta-github** [comment]
`EnableBadSignatureProtection` is not set in our config profile for santa.

**Comment by np5** [comment]
Sorry, I thought is sounded familiar. I have a Printer proxy that santa blocks on my computer (12.5.1), but the signature is reported as  `Code-signed: Yes, but can't validate as Info.plist is missing`.

**Comment by meta-github** [comment]
In fact, santa is not blocking our PrinterProxy, it is macOS Ventura that does not like the broken signature of the app and it prevents the app from starting. The signature gets broken by santa which replaces an adhoc signed binary by something else. That's the analysis of Apple:

`2022-08-23 19:59:31.503835+0200 0x214bfa   Default     0x0                  400    0    com.google.santa.daemon: I com.google.santa.daemon: PrinterProxy workaround applied to: /Users/j905960/Library/Printers/PullPrint.app/Contents/MacOS/PrinterProxy`

**Comment by russellhancox** [comment]
Santa replaces the binary inside the printer app with the original from `/System/Library/PrivateFrameworks/PrintingPrivate.framework` because the adhoc signed one has no significant changes and due to not being signed is not trusted. This workaround is necessary so you don't have to allowlist every printer added to every machine. It looks like Ventura is not happy with this workaround and we'll need to find a replacement workaround

**Comment by np5** [comment]
Another thing I learned today! While trying to understand what was going on, I also noticed that the first time I manually launch the Proxy in the terminal after configuring a printer on 12.5.1 (when it is still the ad-hoc signed version that will be replaced by Santa), it crashes with a code signature error. The second time, it works.

**Comment by np5** [comment]
I do not know it it helps, but I have just tested in a ventura VM, and same thing: the first manual execution after the printer is created, when the binary on disk is still the ad-hoc signed one fails. The second one is successful.

**Comment by russellhancox** [comment]
The behavior np5 describes above is the expected behavior but that is not what I'm seeing on Ventura β1, the OS is killing the copied binary because of a [Launch Constraint](https://theevilbit.github.io/posts/amfi_launch_constraints/) violation. We'll need to look at whether we can work around this as the adhoc signed binary that the OS normally produces will be blocked by hosts in Lockdown mode.

**Comment by meta-github** [comment]
Tested with beta 11, we no longer see PrinterProxy crashing on Ventura, even after Santa (testet with v2022.8) applied the existing workaround. So, it seems that Apple has changed something in macOS Ventura which prevents the bug.
